<h4>Research Project</h4>

<article>
<h5>Impact of Technology on the Homeless</h5>

<ul>
<li>Michael Bessey and Shaun Kelly</li>
<li>Dr. Anthony Townsend</li>
<li>December 12, 2011</li>
</ul>

<section>
<h6>Overview</h6>
<p>Homelessness is a serious issue in America, particularly in urban areas, and while shelter and food are obviously paramount needs, the lack of access to technology creates an increasingly significant divide between the homeless and the mainstream community. This deprivation of technology makes it nearly impossible to attain improvement in their life circumstances. It is our contention that an investment in technology access and education for the homeless will afford the homeless a greater opportunity to take initiative in improving their own circumstances.</p>
<p>The homeless are prominent members of the public within most urban environments and due to this it could be argued that designers of technology have an ethical responsibility to them. According to the first principle of the Association for Computer Machinery’s Software Engineering Code of Ethics and Professional Practice, a software engineer has an ethical responsibility to act with the public interest. In particular, sub-principle 1.07 states that software engineers shall consider issues of physical disabilities, allocation of resources, economic disadvantage and other factors that can diminish access to the benefits of software. (Quinn, 2005, p. 403)</p>
<p>Advances in technology affect all aspects of life including communication and access to information. In Ethics for the Information Age Rawls' second principle of justice requires us to consider whether inequalities are of the greatest benefit to the least-advantaged members of society. (Quinn, 2005, p. 88) Due to this, when we design technology it will be important to avoid the exclusion of anyone by being conscious of both the user and the context in which these technologies will be utilized. For instance the homeless community needs to take advantage of communication to contact social workers and access to information to learn about economic opportunities.</p>
<p>Our research details who makes up the homeless community, how technology is currently being utilized by social workers as well as the homeless, and what technologies are needed in order to afford change in the homeless community.</p>
</section>
<section>
<h6>Demographics</h6>
<p>The U.S. Department of Housing and Urban Development (HUD) defines a person as being homeless if they are either living in a place not meant for human habitation, such as streets, cars, parks, abandoned buildings (unsheltered), or living in an emergency shelter or transitional housing for homeless people (sheltered). </p>
<p>According to HUD’s 2009 Annual Homeless Assessment Report (AHAR), on a single night, over 640,000 people were homeless, of which, one third were unsheltered. Since HUD has been measuring, the number of unsheltered homeless has been trending downward. Approximately two-thirds were individuals and one-third were part of a family. Approximately 110,000 people are chronically homeless. The 2009 AHAR also specifies that nearly 1.5 million people were considered sheltered homeless at some point during the year. Of this 1.5 million, 64% were alone, 61% were male and 62% were a minority. </p>
<p>The U.S. Conference of Mayor's Task Force on Hunger and Homelessness identified the top causes of homelessness as unemployment, lack of affordable housing, poverty, domestic violence, and low paying jobs. The task force detailed the following statistics: 24% of homeless adults are severely mentally ill and 20% are physically disabled; 19% are employed and 14% are veterans; 14% are victims of domestic violence and 3% are HIV positive. Many fall into multiple categories. The task force also stated that 27% of persons requesting shelter do not receive it due to lack of capacity.</p>
</section>
<section>
<h6>How the Homeless Use Technology</h6>
<p>Many homeless people are resourceful in the ways they use technology to improve their lives. We found several themes in our research regarding how the homeless make use of technology. The first theme was the importance of maintaining social connections and establishing a support infrastructure. Le Dantec and Edwards (Designs on Dignity 2008) interviewed several participants who stated that they experienced a great deal of stress when disconnected from an extended social circle. Many were concerned that something would happen to loved ones and they wouldn’t know it. Also, homeless individuals found it critical for survival to find friends they could trust, finding safety in numbers. Maintaining contact with their caseworker was also important, as the caseworker played a central role in the lives of the participants. Due to the fact that several of the participants were illiterate or suffered from various mental disabilities, the caseworker helped explain the system, setup appointments, and fill in the forms.</p>
<p>In order to maintain these social connections all of the participants had voicemail accounts through local organizations. Although these accounts were intended to be a stable contact number, participants preferred to use a cell phone. Without a cell phone, accessing their account involved a difficult daily activity of traveling to the organization and waiting in line to use the service. Several of the participants stated that they would not sell their cell phone for money; however, they found difficulties with having a cell phone, such as the ongoing cost and the need to access power in order to recharge the phone. Instead of fixed monthly contract, participants desired cell phones that were on a pay-as-you-go plan.</p>
<p>Roberson and Nardi (2010) conducted interviews and observed a number of homeless people in Los Angeles’ Skid Row area. One participant, a man who had been homeless for six months, owned a laptop and a cell phone, which he used for a number of things. He used Craigslist to find people looking for casual sex partners. He would meet the people at their places for sex, enabling him to have a place to shower and to sleep for the night, usually a meal, as well as meeting his sexual needs. He was able to do this without these people knowing he was homeless. He was also exposed to some of the dangers of having technology when homeless, as he had two laptops stolen during his time on the street. He also noted how important it was to have a cell phone to stay in contact with employers, his psychiatrist, and “different officials.” Before having a cell phone, he used Skype on his laptop to stay in touch.</p>
<p>A homeless woman who was also interviewed described the importance of having a cell phone in terms of the limitations of using the phone at the shelter. The shelter only allowed you five minutes for a call on its phone, which was not enough to take care of personal business.</p>
<p>Roberson and Nardi also discussed the Skid Row Photography Club, where a group of homeless people founded the club and found donors to give them cameras. The members of the club took photographs and then came together for meetings and held exhibitions for the larger community in galleries. The members of the club hoped that through the exhibitions, the perceptions of the community would be challenged and the community as a whole would be able to see the club members as human beings with common feelings and tastes, not simply as part of the “other.”</p>
<p>We interviewed Heather Huang (2011) who is a Licensed Clinical Social Worker and supervises case workers for a hospital in The Bronx, New York City. Her department works with the homeless, mainly single men, who have histories of substance abuse. Her clients are in unstable living conditions either living on the streets, in crowded family situations, in unregulated boarding houses or are living in shelters such as Bellevue Men's shelter or the Wards Island Men's shelter.</p>
<p>Huang referenced computers at the public library as the main accessible source of technology for the homeless, although, there are a couple programs in which you can get a free cell phone if you have Medicaid. Most of Huang's clients are able to get these cellphones, although, these cell phones are only allotted so many minutes per month. Agencies used to offer voicemail accounts to homeless individuals; however, they discontinued the program in light of the free cell phones. This has not worked out well for people who don't have access to the free cell phone program. Her clients who do have cell phones have to constantly check their batteries and remember to plug in their phones whenever they get the chance. There is not always a publicly accessible place to plug in, and, if they lose their cord, they’re in trouble. Often the first thing that clients do when they come into Huang's office is plug in their phone. (H. Huang, personal communication, December 7, 2011)</p>
<p>Huang was not aware of any of her clients using technology to maintain social connections. Text messaging is not an available feature on the free cell phone plans and because the time one can spend on the Internet at the public library is restricted she doesn't imagine that her clients would have the time to use an Internet based social network such as Facebook.</p>
<p>A second theme uncovered by our research was in how the homeless use technology as a means of protection. Woelfer et al. (2011) looked at the experience of homeless youths in the U-District in Seattle. The homeless youths indicated a wide variety of ways in which cell phone use could keep them safe. Interestingly, they largely ignored the possibility of using phones to call the authorities for help as they have an antagonistic view of the authorities due to the responsibility of the police for enforcing anti-camping and anti-loitering laws. One youth mentioned that his friends called to let him know the police were on the way so that he could hide his marijuana. Another said he could use his phone to record police if they were harassing him. A female mentioned that having a cell phone could keep you safe from predators because people would know that you could call the authorities, although she didn’t suggest that she would be likely to do so. One of the service providers mentioned a story in which a homeless female was able to take a picture of a man who was sexually harassing her and forward it to the service providers and police.</p>
<p>On the other hand, the youths also understood some of the perils of having technology in their situation. One mentioned the possibility that he could get beat up for snitching for using his phone to call the police. Another explained that having too nice a phone would actually make you more likely to be a victim as you would be a target for robbery. </p>
<p>Our research also identified as a theme the significance placed by the homeless on managing presentation of self and mitigating the social stigma of homelessness. Le Dantec and Edwards (Designs on Dignity 2008) discussed with one participant on how he used his cell phone as a social symbol. This participant was careful about who he would tell about being homeless, and, because he had a cell phone, his friends were unlikely to make the connection that he was struggling and living on the street. Another participant regularly used the Internet at the public library to access his MySpace account. In utilizing this stable technology based form of communication it allowed the participant to maintain connections without revealing that he was homeless.</p>
<p>Finally there was a general lack of experience with technology within the homeless community. Le Dantec and Edwards observed that their participants were either perplexed or expressed disinterest when asked questions about computers.</p>
<p>The technology training available to the homeless in New York provided by the Department of Labor includes free computer training courses, according to Huang.  She stated that there are also state-funded technology training programs, however, for a number of reasons, few people take advantage of them. One reason is that when dealing with finding shelter and food, computer training is less of a concern. Another reason is that the technology itself can be overwhelming to people with limited exposure to computers.  She stated, “I think a lot of our clients would be very frustrated having to do Google searches. We’ll do them for them often times, but the Internet is a whole other world they don’t have a lot of familiarity with. Even getting an email address and sending off a resume."</p>
<p>She went on to describe her clients as very uncomfortable with technology. When she tells her clients that they need an email address to apply for jobs and receive response, many of them get really upset. Huang contributes a lot of these fears to the fact that her clients are behind educationally. Many struggled in school, often leaving before finishing high school, and are intimidate by the idea of learning technology. She notes that, “intimidation is a little bit higher of an issue then even access would be. Because they do know where they can access it, it’s that they’re afraid to do it."</p>
<p>When asked if she feels the trend is changing with children of homeless families, Huang said that it mainly depends on the school that the children are attending. A lot of schools are now equipped with computers; however, homeless situations are really tough on kids:</p>
<blockquote>Kids who are homeless also experience a lot of stress... They really experience what their parents are going through and it’s difficult for them to concentrate. It was an issue when I worked in a family shelter. They would have behavior problems and they would have had to switch schools sometimes a couple of times while they were in the homeless situation.</blockquote>
</section>
<section>
<h6>Homeless Support Technology</h6>
<p>While we have shown how important technology is to the homeless community, the organizations that support homeless people; such as shelters, clinics, job placement centers, and charities, have their own challenges in accessing technology in pursuit of their goals.</p>
<p>Le Dantec and Edwards (2008) observed two different homeless outreach organizations to understand how technology is currently used, and could be utilized, to improve cooperative work. Due to the limited funding typical of non-profits and government organizations, these organizations need to adopt technology solutions to increase their efficiency in gathering funds, delivering services, and coordinating their work internally and with other groups. However, due to limited funding, they have limited access to technology and what they do have is generally outdated.</p>
<p>While Huang’s (2011) organization in New York City is provided with nice computer systems to those working in the office, unfortunately those in the field only recently received cell phones and do not have computer access. Therefore, they have to wait until they are back in the office to input important information, thus wasting valuable time and possibly losing important details.</p>
<p>Le Dantec and Edwards also found that there is limited technological expertise available. This is largely because the support organizations must rely on volunteer workforces that may have limited skills in technology to begin with, and require constant retraining due to volunteer turnover.</p>
<p>They also found that the major technology needed within organizations was shared information spaces to define responsibilities for the staff and volunteers, centralize scheduling of appointments and data access for answering questions from clients. One of the organizations they looked at relied heavily on computer mediated communications such as email and instant messaging. This was largely to provide a record of the conversation and to ensure that they were able to reach everyone within the organization.</p>
<p>Technology could be utilized by these organizations in many ways to enable them to better serve the population. Le Dantec et. al (2010) developed a Community Resource Management (CRM) tool in collaboration with the residents and staff at an emergency night shelter for homeless women and their children. The components of the system included a messaging system that shelter staff could use to send messages to residents’ cell phones, SMS and voice mail access that allowed residents to request information and assistance, with a shared message board display for the shelter. The residents of the shelter largely had some technological savvy including cell phone and Internet usage and used SMS to maintain social contacts with family and friends.</p>
<p>Although the system Le Dantec et al. implemented was a simple messaging system, the system had a number of effects on the shelter. Residents were able to move beyond their understanding of mobile technology as a tool for social communication to a tool with utility to improve their lives. Shelter staff were able to extend their contact with residents to times when residents were not at the shelter; likewise, residents were able to access shelter resources outside of times when they were present at the shelter.  The tool even affected how staff communicated with residents while at the shelter, sometimes choosing messaging over face-to-face contact as a method of avoiding confrontation. The dynamic nature of the shared message board made it a more useful source of posting information than existing cork boards.</p>
<p>Outreach groups often focus on a specific area of expertise (mental health, employment, childcare, etc.) and homeless people may need to access support from a number of groups to meet all of their needs. Because of this, coordination is important both within an organization and amongst the broader community. Both organizations studied by Le Dantec and Edwards (2008) were currently using a web-based case management system call Pathways, as mandated by law. The system is used to coordinate information for a single client among different providers. Both groups found difficulties in using the software due to slow access issues or random characters used to define other organizations, and also found themselves often needing to duplicate data entry into multiple systems. The software, however, allowed them to see what care was provided to an individual by all different groups. This was used as intended to coordinate care, but also used to prevent abuses of the system. One major downside of Pathways was that the system only allowed sharing information about received aid, not additional notes about client needs. Part of this is because of legal and moral concerns about privacy for the homeless clients. However, it made coordinating care much more difficult.</p>
<p>It is clear then that technology as it stands, for both the homeless and those that care for them, is at best lacking and will need major improvements to impact the situation of the homeless community in a positive way.</p>
</section>
<section>
<h6>Recommendations</h6>
<p>Our research indicates that cell phones are the most crucial piece of technology for homeless people who have access to them, allowing them to keep in contact with case workers, family, and employers. Free voicemail services, widely available to the homeless, are of limited use. Unfortunately, for a combination of financial reasons and fear of technology, many homeless people do not have access to cell phones. Service organizations should consider providing access to cellphones as a top priority in terms of technology programs for the homeless.</p>
<p>The homeless have particular needs for cellphones that differ from the general public which should be taken into consideration when choosing which phones to provide. Woelfer et al. indicated a number of criteria desired by their subjects, including low cost, durability, flexible power options, and means for recovery when lost or stolen. Their subjects were also particularly interested in having recording capabilities to enable them to document abuses as well as some sort of panic button to allow them to contact authorities without arousing the suspicions of the people around them. Multiple sources indicate that keeping phones powered is one of the biggest challenges the homeless face, so choosing phones with excellent battery life is especially important. Additionally, providing access to power outlets in public locations would be helpful.</p>
<p>Flexible pricing is important to allow the user to pre-pay for minutes instead of being tied to a fixed monthly contract. This plan should also allow for extended periods of time where the phone is not being used, perhaps for periods up to 6 months, while being able to retain the same phone number.</p>
<p>In addition to phones, as our interview with Huang indicated, access to computers and the necessary skill set to utilize them are important. Particularly for the homeless to access job services, apply for jobs, get feedback from potential employers and look for housing. Roberson and Nardi showed several examples of how the homeless were able to use computers to improve their situations. However in order for this to occur improvement is necessary in access to computer terminals and training.</p>
<p>While we saw a few examples of homeless people who owned their own laptops, most homeless computer users relied on public computers, particularly in libraries. Because of this, local governments should particularly consider the effects of any restrictions on computer use in libraries on the homeless and choose the least restrictive policies.</p>
<p>However, for many homeless people access to computers is limited by skill, not physical access. Service providers should make training available for these people. As Huang noted, some people are unable to take advantage of basic computer training that is already available. Training should be designed to be sensitive to the fears of technical novices and to highlight the benefits of learning.</p>
<p>Homeless support service organizations could also benefit from a number of initiatives to maximize their technology use. These organizations need better training on computer skills so that employees and volunteers can take advantage of these services. They also need technology choices laptops, tablets or smart phones that enable employees and volunteers to do effective work in the field.</p>
<p>Additionally, as Le Dantec et al’s CRM trial showed, enabling clients of the service providers to contribute to and access shared information space benefits both the clients and the providers. Services to coordinate between providers are already in place in some areas; however, these services can be improved in terms of usability and the types of information shared. </p>
</section>
<section>
<h6>Conclusion</h6>
<p>When the homeless are lacking basic needs such as food and shelter, one might ask why worry about their technology use. We believe technology is a necessity in order to function in modern society; it is the standard method by which our society communicates and shares information. Technology will drive the advancement of society and if the disadvantaged members of society are not able to make use of technology, they will be left behind.</p>
<p>While, we can teach technology in the classroom, technology is constantly evolving. Only people who are exposed to technology on a daily basis will be able to maintain comfort with technology and have the opportunity to realize the benefits that can be gained from its use. Until we are able to make technology ubiquitously accessible to the homeless, they will never be able to fully take advantage of it and the cycle of intimidation will continue.</p>
<p>Therefore, as practitioners of human-computer interaction, we should be conscientious of all humans as we design new technologies, regardless of their social or economic status, in order to bridge the technical divide.</p>
</section>
<section>
<h6>References</h6>
<p>Bosman, J. (2009, July 28). City Aids Homeless With One-Way Tickets Home. Retrieved from <a href="http://
www.nytimes.com/2009/07/29/nyregion/29oneway.html" target="_blank">http://
www.nytimes.com/2009/07/29/nyregion/29oneway.html</a></p>
<p>C. A. Le Dantec. Feature: Life at the Margins: Assessing the Role of Technology for the Urban
Homeless. interactions, 15(5):24–27, 2008.</p>
<p>C. A. Le Dantec and W. K. Edwards. Designs on Dignity: Perceptions of Technology Among the
Homeless. In CHI ’08: Proceeding of the twenty-sixth annual SIGCHI conference on Human
factors in computing systems, pages 627–636, New York, NY, USA, 2008. ACM.</p>
<p>C. A. Le Dantec and W. K. Edwards. 2008. The view from the trenches: organization, power, and
technology at two nonprofit homeless outreach centers. In Proceedings of the 2008 ACM
conference on Computer supported cooperative work (CSCW '08). ACM, New York, NY, USA,
589-598. DOI=10.1145/1460563.1460656</p>
<p>C. A. Le Dantec, R. G. Farrell, J. E. Christensen, M. Bailey, J. B. Ellis, W. A. Kellogg, and W. K.
Edwards. Publics in Practice: Ubiquitous Computing at a Shelter for Homeless Mothers. In
CHI ’11: Proceeding of the twenty-nineth annual SIGCHI conference on Human factors in
computing systems, pages 1687–1696, New York, NY, USA, 2010. ACM.</p>
<p>Coalition for the Homeless. (2011, November). Basic Facts About Homelessness: New York City.
Retrieved from <a href="http://www.coalitionforthehomeless.org/pages/basic-facts-about-homelessness-
new-york-city" target="_blank">http://www.coalitionforthehomeless.org/pages/basic-facts-about-homelessness-
new-york-city</a></p>
<p>Interview of Heather Huang by Michael Bessey. New York City. December 2011.</p>
<p>Jahmeilah Roberson and Bonnie Nardi. 2010. Survival needs and social inclusion: technology
use among the homeless. In Proceedings of the 2010 ACM conference on Computer
supported cooperative work (CSCW '10). ACM, New York, NY, USA, 445-448.
DOI=10.1145/1718918.1718993 <a href="http://dl.acm.org.proxy.lib.iastate.edu:2048/citation.cfm?
id=1718918.1718993&coll=DL&dl=ACM&CFID=52109534&CFTOKEN=59131100" target="_blank">http://dl.acm.org.proxy.lib.iastate.edu:2048/citation.cfm?
id=1718918.1718993&coll=DL&dl=ACM&CFID=52109534&CFTOKEN=59131100</a></p>
<p>Jill Palzkill Woelfer, Amy Iverson, David G. Hendry, Batya Friedman, and Brian T. Gill. 2011.
Improving the safety of homeless young people with mobile phones: values, form and function.
In Proceedings of the 2011 annual conference on Human factors in computing systems
(CHI '11). ACM, New York, NY, USA, 1707-1716. DOI=10.1145/1978942.1979191 <a href="http://
doi.acm.org/10.1145/1978942.1979191" target="_blank">http://
doi.acm.org/10.1145/1978942.1979191</a></p>
<p>Michael J. Quinn, Ethics for the Information Age (2nd Edition), Addison-Wesley Longman Publishing
Co., Inc., Boston, MA, 2005</p>
<p>The United States Conference of Mayors. (2010, December). Hunger and Homelessness
Survey. Retrieved from <a href="http://www.usmayors.org/pressreleases/uploads/2010_Hunger-
Homelessness_Report-final%20Dec%2021%202010.pdf" target="_blank">http://www.usmayors.org/pressreleases/uploads/2010_Hunger-
Homelessness_Report-final%20Dec%2021%202010.pdf</a></p>
<p>U.S. Department of Housing and Urban Development Office of Community Planning and Development.
(2010, June). The 2009 Annual Homeless Assessment Report to Congress. Retrieved from <a href="http://
www.huduser.org/publications/pdf/5thHomelessAssessmentReport.pdf" target="_blank">http://
www.huduser.org/publications/pdf/5thHomelessAssessmentReport.pdf</a></p>
</section>
</article>