<h4>Research Project</h4>

<article>
<h5>The Psychology of Gamification in the Workplace</h5>

<ul>
<li>Michael Bessey and Rich Tanner</li>
<li>Dr. Jon Kelly</li>
<li>December 10, 2011</li>
</ul>

<section>
<h6>Overview</h6>
<p>Gamification is the use of game-like mechanics and design techniques to enhance or stimulate engagement in an otherwise non-game-related activity.  This study will examine the research and experimentation in gamification as it is related to the workplace, and attempt to measure the success of businesses employing gamification techniques to train employees and to encourage desirable behaviors.  The research will also demonstrate the need for an understanding of the psychological motivating factors for each employee, in order to properly incentivize any task.  Furthermore, we will investigate how gamification directly impacts the aspects of cognition that are necessary in the workplace for high performance, such as concept learning and problem solving.</p>
</section>
<section>
<h6>Background Research - Gamification in Education</h6>
<p>In the article entitled, Games, motivation, and learning: A research and practice model, authors Garris, Ahlers and Driskell&apos;s research in the area of game mechanics within an instructional environment provide support for the effectiveness of simulation games as training tools.  It demonstrates that computer game play can be both an intrinsic and extrinsic motivator of behavior within a learning context.  The studies performed in the research indicate that students who used simulation games demonstrated improved performance over those who received instructional training alone.  This research also proved that game mechanics within an instructional environment caused students to become enthusiastic, focused and engaged.  This is due to the student becoming driven of their own volition because they both desire the education they will gain, and because the instructional game is in itself interesting.  Additionally, game-like simulations provide feelings of accomplishment and achievement, which serves to incentivize not only the <q>playing</q> of such games, but the learning of lessons contained within, which makes the learner a better <q>player</q> the next time he or she is confronted with similar scenarios or <q>levels</q> (Garris, Ahlers &amp; Driskell, 2002).</p>
<p>Erik Van Der Spek&apos;s research in COgnition-based DEsign Rules Enhancing Decisionmaking TRaining In A Game Environment (Code Red Triage) hypothesizes that a better learning experience can be provided, while preventing cognitive overload, if the learning is couched in a compelling narrative.  Further, the researcher proposes that by <q>deliberately introducing information gaps</q>, the players mind will actively work to fill those gaps resulting in richer and more reinforced learning.  These theories were explored through the use of a specially designed game-like simulation intended to train paramedics and ambulance workers.  Based on the popular Source Engine by VALVe, Code Red Triage is a modification of the first-person game Half Life 2, which immerses potential paramedics in realistic catastrophic triage scenarios.  Applying his hypothesis, Van Der Spek trickles necessary information to his players, providing just enough of a hook to achieve engagement and to allow the players to fill in the <q>information gaps</q> with the knowledge they have already acquired through their common, and more traditional, professional training (Van Der Spek, 2010).  This type of learning goes beyond mere rote memorization of facts and actually helps learners to form and reinforce vital connections between facts, propelling knowledge into valued wisdom.</p>
<p>Lisk, Kaplancali and Riggio, in their article entitled, Leadership in Multiplayer Online Gaming Environments Simulation &amp; Gaming, propose that desirable leadership qualities are being <q>accidentally</q> learned by players engaging in the social interactions inherent in Massively Multiplayer Online (MMO) games that are designed for entertainment.  In order to successfully navigate the virtual multiplayer environments, players must work cooperatively with other players, often over great distances, to accomplish their common goals.  In these virtual group dynamics, it becomes necessary for one or more players to <q>step up</q> to a leadership role and coordinate the efforts of the group.  Through the trial and error of the group&apos;s various campaigns, a tried and true online <q>leader</q> is molded.  Thus, popular online entertainment titles such as World of Warcraft, Everquest and EVE ONLINE have become both precursors and proving grounds for collaborative distance teams and for virtual leadership.  This leadership and cooperation training has been successfully replicated in online <q>gaming</q> simulations such as Americas Army and Full Spectrum Warrior, both of which were developed for military use, and has been explored in a myriad of other industries as well, as we have already seen.  Another simulation, INFINITEAMS, is applying such leadership training to <q>Distributed Teams</q> whose primary interaction is though a combination of distance based online interactions (Lisk, Kaplancali &amp; Riggio, 2011).  Tailored for business use, INFINITEAMS was built by Scottish company Team Play Learning Dynamics (TPLD) and integrates computer game design theory and the psychology of team dynamics and learning to simulate a remote island whereupon <q>groups of individuals will find themselves communicating, collaborating and embracing the behavior of highly effective teams</q> (<q>Team Building</q>, 2004).</p>
<p>Pasin and Giroux, the authors of The Impact of a Simulation Game on Operations Management Education, concluded that simulation games are most effective in helping students develop decision-making abilities for managing complex and dynamic situations while understanding the systemic effects and unintended consequences of their decisions.  Some concepts cannot fully be grasped until they have been experienced.  Simulation games better represent real-life situations in operations management and allow the users to learn and make mistakes within a realistic environment free from consequences.  Despite the positive results obtained from simulation game training these researchers felt that simulation games should not replace but augment traditional teaching methods (Pasin &amp; Giroux, 2011).</p>
<p>The benefits of training augmentation from applied gamification techniques appear to be limitless.  Whether applied in the classroom, the medical field, for military use or for business use, all of the above research touted positive results of gamification in training.  The game mechanics employed provided enhanced motivation to complete the training, and produced more engagement, focus and enthusiasm.  The extra level of immersion provided enjoyment while the players were learning new facts or skills or reinforcing what they already knew, and by carefully controlling the flow of information, designers were able to stimulate players&apos; own brains into filling in the <q>gaps</q>.  The simulation of a real team within a shared virtual environment encouraged healthy group interactions and provided valuable leadership training and teamwork as groups worked toward common goals.  And the careful construction of virtual scenarios allowed players to learn through experience, free to explore possibilities without fear of real-world consequences.  It is little wonder that such software is being utilized within the modern workplace.  What company wouldn&apos;t want focused, confident, engaged, team players and leaders who can think beyond the boundaries of traditional business?</p>
</section>
<section>
<h6>Future Directions</h6>
<p>Traditional education prepares an individual with a foundation of knowledge that can be applied to wide range of professions; however, the corporate landscape is a more complicated environment than the classroom.  The corporate landscape is full of complex and dynamic situations where a decision made by an employee can have systemic effects and unintended consequences.  Currently, people must learn the skills necessary to become proficient within this environment while on the job where mistakes can be costly.</p>
<p>Based on our research it would seem that simulation games would be a valuable resource to address this problem.  A corporation could use a simulation game tailored to imitate the day-to-day challenges of a specific industry in order to augment an employee&apos;s traditional education and prepare them for the specific demands of their profession.  A corporation could use this tool to train interns who are just learning the ropes or to evaluate an applicant&apos;s potential performance before hiring them for the position.  A seasoned employee interested in advancing their career could also use the training software.  If the employee is given a task that they have not encountered before, the software would provide the employee with access to training simulations tailored to the areas of competence in which the employee needs to improve.  The training simulations would improve employee proficiency and upon completion count towards future promotions.</p>
<p>As pointed out by the research, simulation games can represent real-life situations in operations management and allow players to learn and make mistakes within a realistic environment free from consequences.  If the U.S. Military feels that simulation games are a valuable tool in preparing soldiers for combat it would stand to reason that simulation games could prepare employees for the daily challenges that occur within a business.</p>
<p>Furthermore, the manner in which we are taught conditions us on how we will continue to learn throughout our lives and the workplace is indeed a perpetual learning environment where every challenge we encounter is an opportunity to gain knowledge and experience.  We envision that the same application used to train employees with realistic simulations could also be used to manage the progress of employees in the workplace.  The same gaming mechanics, which our research demonstrates works well in a training environment, could also translate into effective management techniques.  Because each employee has become familiar with the application during their training sessions it should be a smooth transition for each employee to use the application as a guide to direct their actions within the workplace.  If successful, the representation of a game within the application would be indistinguishable from the representation of a real-life workplace scenario.  This application would be a realization of the fictionalized battle simulator in the book Ender&apos;s Game by Orson Scott Card.</p>
<p>Because the measurement for success within a simulation game is determined by a numerical score, one could argue that an application that operates as a simulation game could not also function as management software because not all actions within a corporation can be quantified.  An example of such an action would be when an employee successfully placates an unsatisfied customer.  However, all organizations or companies have strategic business objectives or goals defined by the stakeholders.  The purpose of management within an organization is to direct the actions of their employees towards these business objectives because the success of an organization is indicated by the continual achievement of these goals.  An industry term for the method used to measure progress towards an organizational goal is KPI (Key Performance Indicators).  Key Performance Indicators are quantifiable measurements that reflect the organization&apos;s progress towards critical success factors.  When KPIs are well defined they provide employees with clear objectives that relate directly to the success of the organization.</p>
<p>Conceivably, the chief operating officers within an organization could enter the key performance indicators into the game-like management software.  Then the management at each level of the organization would define employee goals that would align with, and support, these key performance indicators.  Each employee would have a clear view within this software of how their daily activities align with the company&apos;s objectives.</p>
<p>Examples of KPIs could include: 1) The student graduation rate at a University.  2) The number of new customers acquired by a marketing firm.  3) The number of defects within products produced by a manufacturing line.</p>
<p>A training simulation to be administered within the application could be configured with the KPIs of the previous year.  A group of employees would be run through the training simulation and would be evaluated on whether they are able to match or exceed the historical performance of their department.  During simulation training, as well as for certain work challenges, the software could present a leader board where an employee can see how he ranks in comparison to his co-workers.  The employee would be motivated by competition to work harder and rise above his co-workers on the leaderboard.</p>
<p>An example of this would be when software engineers are resolving defects in a new software system before release, the software engineers that have resolved the largest number of issues would be ranked at the top of the leader board.  This management software would provide constant feedback to the employee through performance indicators and incentivize the employee by giving them clear goals as how to achieve their next promotion.  It also allows the employee to see exactly how they are being evaluated, without a question of whether ratings are simply subjective.</p>
<p>Gamifying management will not work unless there is a commitment by the management team to define thoughtful incentives and design a realistic leveling system.  This management software will only contribute to the success of an organization if the management is committed to constantly refining the rules of the system.  A manager should define levels and provide the employee with job related tasks that are appropriate for their skill level.  These levels or goals should gradually increase in difficulty in order to appear achievable and avoid discouraging the employee from progressing.  Also, each employee will be motivated by different incentives, and it would be up to management to ascertain the different psychological motivating factors for each employee they work with.  The software would be flexible enough to allow managers to define different incentive options for each objective, then the employee would be able to choose what reward he or she would like to receive for achieving a certain objective.  The manager would have to make sure that they are specifying incentives that are actually appealing to their employees.  Fun elements could also be incorporated into this management software such as allowing employees to upload personalized avatars and customize their account page.  Indeed, many companies are already incorporating personalizable <q>profiles</q> pages within their organizations intra-net, signaling a move toward such an idea.</p>
<p>Finally, there is a stigma, especially among non-gamers, that any game related activities are a waste of time.  However, the purpose of this gamified management software is to take game principles that have been proven to be excellent motivating factors and apply them towards motivating employees to achieve valuable real-life objectives in business.  It is our conjecture that the use of an employee management/training application, based on the research we uncovered, would increase levels of competency, heighten productivity and enhance satisfaction among employees within the corporate environment.</p>
</section>
<section>
<h6>References</h6>
<p>Federico Pasin, Hélène Giroux, The impact of a simulation game on operations management education, Computers &amp; Education, Volume 57, Issue 1, August 2011, Pages 1240-1254, ISSN 0360-1315, 10.1016/j.compedu.2010.12.006.</p>
<p>Garris, R., Ahlers, R., &amp; Driskell, J. E. (2002). Games, motivation, and learning: A research and practice model. Simulation &amp; Gaming, 33(4), 441-467.2004-16731 -00210.1177 /1046878102238607</p>
<p>Team building - infiniteams. (2004, May 18). Retrieved from <a href="http://www.socialimpactgames.com/modules.php?op=modload&name=News&file=article&sid=214" target="_blank">http://www.socialimpactgames.com/modules.php?op=modload&amp;name=News&amp;file=article&amp;sid=214</a></p>
<p>Timothy C. Lisk, Ugur T. Kaplancali, and Ronald E. Riggio
Leadership in Multiplayer Online Gaming Environments Simulation &amp; Gaming January 19, 2011 1046878110391975, first published on January 19, 2011 doi:10.1177/1046878110391975.</p>
<p>Van Der Spek, Erik D. <q>Cognition-based Design Rules Enhancing Decision making Training In A Game Environment (Code Red Triage): doctoral consortium paper.</q> ECCE &apos;10 Proceedings of the 28th Annual European Conference on Cognitive Ergonomics. New York, NY, USA. ACM. 2010. 319-322. Print.</p>
</section>
</article>